server:
  port: 8585

spring:
  application:
    name: jwt-implementation
  datasource:
    url: ${POSTGRES_LOCALHOST}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PW}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


# Definir las variables para el JWT
application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: 86400000 #1 dia